//Dummy Data
import logo from "../../public/images/logo.png";

const pointsTableData1 = [
  {
    AgainstTeam: "2395/250.5",
    Category: null,
    CompetitionID: "203",
    Deficit: "0",
    Draw: "0",
    ForTeams: "2447/246.4",
    IsQualified: "1",
    LeadBy: "0",
    Loss: "4",
    MATCH_ID: "1867",
    Matches: "14",
    NetRunRate: "0.372",
    NoResult: "1",
    OrderNo: "1",
    Performance: "W,W,W,L,W",
    Points: "19",
    PrevPosition: "1",
    Quotient: "1.075",
    StandingFlag: "NET",
    Status: "SAME",
    TeamCode: "PBKS",
    TeamID: "15",
    TeamLogo:
      "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/teamlogos/PBKS.png?v=2",
    TeamName: "Punjab Kings",
    Tied: "0",
    Wins: "9",
  },
  {
    AgainstTeam: "2520/255.2",
    Category: null,
    CompetitionID: "203",
    Deficit: "0",
    Draw: "0",
    ForTeams: "2480/248.0",
    IsQualified: "1",
    LeadBy: "0",
    Loss: "3",
    MATCH_ID: "1868",
    Matches: "14",
    NetRunRate: "0.412",
    NoResult: "0",
    OrderNo: "2",
    Performance: "L,W,W,W,W",
    Points: "18",
    PrevPosition: "2",
    Quotient: "1.102",
    StandingFlag: "NET",
    Status: "UP",
    TeamCode: "MI",
    TeamID: "16",
    TeamLogo: logo,
    TeamName: "Mumbai Indians",
    Tied: "0",
    Wins: "9",
  },
  {
    AgainstTeam: "2470/251.3",
    Category: null,
    CompetitionID: "203",
    Deficit: "0",
    Draw: "0",
    ForTeams: "2401/244.5",
    IsQualified: "0",
    LeadBy: "0",
    Loss: "5",
    MATCH_ID: "1869",
    Matches: "14",
    NetRunRate: "0.123",
    NoResult: "0",
    OrderNo: "3",
    Performance: "W,L,W,L,W,",
    Points: "16",
    PrevPosition: "3",
    Quotient: "0.989",
    StandingFlag: "NET",
    Status: "SAME",
    TeamCode: "CSK",
    TeamID: "17",
    TeamLogo: logo,
    TeamName: "Chennai Super Kings",
    Tied: "0",
    Wins: "8",
  },
];


//Dummy Schedule Data
const ScheduleDummyData = [
  {
    MATCH_COMMENCE_START_DATE: "2025-04-12",
    RowNo: "1",
    GroundName: "Wankhede Stadium",
    "1FallScore": "201/5",
    "2FallScore": "180/8",
    "1FallOvers": "20.0",
    "2FallOvers": "20.0",
    "1FallWicket": "5",
    "2FallWicket": "8",
    "1RunRate": "10.05",
    "2RunRate": "9.0",
    FirstBattingSummary: "Player A 50, Player B 40",
    SecondBattingSummary: "Player C 60, Player D 30",
    AwayTeamID: "15",
    HomeTeamID: "16",
    HomeTeamLogo:
      "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/teamlogos/PBKS.png?v=2",
    AwayTeamLogo:
      "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/teamlogos/PBKS.png?v=2",
    FirstBattingTeamName: "Mumbai Indians",
    SecondBattingTeamName: "Chennai Super Kings",
    HomeTeamName: "Mumbai Indians",
    AwayTeamName: "Chennai Super Kings",
    Comments: "Match ended in thriller!",
    FirstBattingTeamCode: "MI",
    SecondBattingTeamCode: "CSK",
    WinningTeamID: "16",
    city: "Mumbai",
  },
  {
    MATCH_COMMENCE_START_DATE: "2025-04-12",
    RowNo: "2",
    GroundName: "Wankhede Stadium",
    "1FallScore": "201/5",
    "2FallScore": "180/8",
    "1FallOvers": "20.0",
    "2FallOvers": "20.0",
    "1FallWicket": "5",
    "2FallWicket": "8",
    "1RunRate": "10.05",
    "2RunRate": "9.0",
    FirstBattingSummary: "Player A 50, Player B 40",
    SecondBattingSummary: "Player C 60, Player D 30",
    AwayTeamID: "15",
    HomeTeamID: "16",
    HomeTeamLogo:
      "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/teamlogos/PBKS.png?v=2",
    AwayTeamLogo:
      "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/teamlogos/PBKS.png?v=2",
    FirstBattingTeamName: "Mumbai Indians",
    SecondBattingTeamName: "Chennai Super Kings",
    HomeTeamName: "Mumbai Indians",
    AwayTeamName: "Chennai Super Kings",
    Comments: "Match ended in thriller!",
    FirstBattingTeamCode: "MI",
    SecondBattingTeamCode: "CSK",
    WinningTeamID: "16",
    city: "Mumbai",
  },
];
